import type { BoardTile } from "~/types/board";

export const BOARD_TILES_ES: BoardTile[] = [
  { index: 0, type: "corner", group: "go", name: "Salida", color: "#28b463" },
  { index: 1, type: "property", group: "brown", name: "Ronda de Arrieta", price: 60, color: "#955436" },
  { index: 2, type: "card", group: "community", name: "Arca Comunal", color: "#3aa6e0" },
  { index: 3, type: "property", group: "brown", name: "Plaza de Lavapies", price: 60, color: "#955436" },
  { index: 4, type: "tax", group: "tax", name: "Impuesto s/Renta", shortName: "Impuesto", color: "#5a5a5a" },
  { index: 5, type: "railroad", group: "railroad", name: "Estacion Norte", price: 200, color: "#2b2b2b" },
  { index: 6, type: "property", group: "lightBlue", name: "Calle de la Montera", shortName: "La Montera", price: 100, color: "#aae0fa" },
  { index: 7, type: "card", group: "chance", name: "Suerte", color: "#f7941d" },
  { index: 8, type: "property", group: "lightBlue", name: "Calle de Alcala", price: 100, color: "#aae0fa" },
  { index: 9, type: "property", group: "lightBlue", name: "Gran Via", price: 120, color: "#aae0fa" },
  { index: 10, type: "corner", group: "jail", name: "Carcel", shortName: "Carcel", color: "#e67e22" },
  { index: 11, type: "property", group: "pink", name: "Paseo del Prado", price: 140, color: "#d93a96" },
  { index: 12, type: "utility", group: "utility", name: "Cia. Electrica", shortName: "Electrica", price: 150, color: "#9ed1a6" },
  { index: 13, type: "property", group: "pink", name: "Calle de Serrano", price: 140, color: "#d93a96" },
  { index: 14, type: "property", group: "pink", name: "Paseo de Recoletos", price: 160, color: "#d93a96" },
  { index: 15, type: "railroad", group: "railroad", name: "Estacion Este", price: 200, color: "#2b2b2b" },
  { index: 16, type: "property", group: "orange", name: "Calle de Goya", price: 180, color: "#f7941d" },
  { index: 17, type: "card", group: "community", name: "Arca Comunal", color: "#3aa6e0" },
  { index: 18, type: "property", group: "orange", name: "Calle de Velazquez", price: 180, color: "#f7941d" },
  { index: 19, type: "property", group: "orange", name: "P. de la Castellana", shortName: "Castellana", price: 200, color: "#f7941d" },
  { index: 20, type: "corner", group: "parking", name: "Parking Gratuito", shortName: "Parking", color: "#c0392b" },
  { index: 21, type: "property", group: "red", name: "Plaza de Espana", price: 220, color: "#ed1b24" },
  { index: 22, type: "card", group: "chance", name: "Suerte", color: "#f7941d" },
  { index: 23, type: "property", group: "red", name: "Calle de Fuencarral", shortName: "Fuencarral", price: 220, color: "#ed1b24" },
  { index: 24, type: "property", group: "red", name: "Paseo de la Reforma", shortName: "Reforma", price: 240, color: "#ed1b24" },
  { index: 25, type: "railroad", group: "railroad", name: "Estacion Sur", price: 200, color: "#2b2b2b" },
  { index: 26, type: "property", group: "yellow", name: "Av. de America", shortName: "America", price: 260, color: "#fef200" },
  { index: 27, type: "property", group: "yellow", name: "Calle Bravo Murillo", shortName: "Bravo Murillo", price: 260, color: "#fef200" },
  { index: 28, type: "utility", group: "utility", name: "Cia. de Agua", shortName: "Agua", price: 150, color: "#9ed1a6" },
  { index: 29, type: "property", group: "yellow", name: "Calle Alberto Aguilera", shortName: "Alberto Aguilera", price: 280, color: "#fef200" },
  { index: 30, type: "corner", group: "gotojail", name: "Ve a la Carcel", shortName: "Ve Carcel", color: "#922b21" },
  { index: 31, type: "property", group: "green", name: "Paseo de Gracia", price: 300, color: "#1fb25a" },
  { index: 32, type: "property", group: "green", name: "Rambla de Cataluna", price: 300, color: "#1fb25a" },
  { index: 33, type: "card", group: "community", name: "Arca Comunal", color: "#3aa6e0" },
  { index: 34, type: "property", group: "green", name: "Avenida Diagonal", price: 320, color: "#1fb25a" },
  { index: 35, type: "railroad", group: "railroad", name: "Estacion Oeste", price: 200, color: "#2b2b2b" },
  { index: 36, type: "card", group: "chance", name: "Suerte", color: "#f7941d" },
  { index: 37, type: "property", group: "darkBlue", name: "Paseo de la Habana", shortName: "La Habana", price: 350, color: "#0072bb" },
  { index: 38, type: "tax", group: "tax", name: "Impuesto de Lujo", shortName: "Lujo", color: "#5a5a5a" },
  { index: 39, type: "property", group: "darkBlue", name: "Paseo del Arte", price: 400, color: "#0072bb" },
];
