import type { BoardTile } from "~/types/board";

// Crestwood City — fictional city, copyright-free board for the English version.
export const BOARD_TILES_EN: BoardTile[] = [
  { index: 0, type: "corner", group: "go", name: "Go", color: "#28b463" },
  { index: 1, type: "property", group: "brown", name: "Watermill Road", shortName: "Watermill", price: 60, color: "#955436" },
  { index: 2, type: "card", group: "community", name: "City Fund", color: "#3aa6e0" },
  { index: 3, type: "property", group: "brown", name: "Harbor Lane", shortName: "Harbor", price: 60, color: "#955436" },
  { index: 4, type: "tax", group: "tax", name: "Income Tax", shortName: "Tax", color: "#5a5a5a" },
  { index: 5, type: "railroad", group: "railroad", name: "North Terminal", shortName: "N.Terminal", price: 200, color: "#2b2b2b" },
  { index: 6, type: "property", group: "lightBlue", name: "Bay Street", shortName: "Bay St", price: 100, color: "#aae0fa" },
  { index: 7, type: "card", group: "chance", name: "Fortune", color: "#f7941d" },
  { index: 8, type: "property", group: "lightBlue", name: "Market Square", shortName: "Market Sq", price: 100, color: "#aae0fa" },
  { index: 9, type: "property", group: "lightBlue", name: "Riverside Walk", shortName: "Riverside", price: 120, color: "#aae0fa" },
  { index: 10, type: "corner", group: "jail", name: "Jail", shortName: "Jail", color: "#e67e22" },
  { index: 11, type: "property", group: "pink", name: "Grand Avenue", shortName: "Grand Ave", price: 140, color: "#d93a96" },
  { index: 12, type: "utility", group: "utility", name: "Power & Light Co.", shortName: "Power Co.", price: 150, color: "#9ed1a6" },
  { index: 13, type: "property", group: "pink", name: "Sunset Boulevard", shortName: "Sunset Blvd", price: 140, color: "#d93a96" },
  { index: 14, type: "property", group: "pink", name: "Palm Drive", shortName: "Palm Dr", price: 160, color: "#d93a96" },
  { index: 15, type: "railroad", group: "railroad", name: "East Terminal", shortName: "E.Terminal", price: 200, color: "#2b2b2b" },
  { index: 16, type: "property", group: "orange", name: "Maple Drive", shortName: "Maple Dr", price: 180, color: "#f7941d" },
  { index: 17, type: "card", group: "community", name: "City Fund", color: "#3aa6e0" },
  { index: 18, type: "property", group: "orange", name: "Oak Street", shortName: "Oak St", price: 180, color: "#f7941d" },
  { index: 19, type: "property", group: "orange", name: "Elm Park", price: 200, color: "#f7941d" },
  { index: 20, type: "corner", group: "parking", name: "Free Parking", shortName: "Parking", color: "#c0392b" },
  { index: 21, type: "property", group: "red", name: "Crown Plaza", shortName: "Crown", price: 220, color: "#ed1b24" },
  { index: 22, type: "card", group: "chance", name: "Fortune", color: "#f7941d" },
  { index: 23, type: "property", group: "red", name: "Empire Square", shortName: "Empire Sq", price: 220, color: "#ed1b24" },
  { index: 24, type: "property", group: "red", name: "Liberty Street", shortName: "Liberty St", price: 240, color: "#ed1b24" },
  { index: 25, type: "railroad", group: "railroad", name: "South Terminal", shortName: "S.Terminal", price: 200, color: "#2b2b2b" },
  { index: 26, type: "property", group: "yellow", name: "Sunrise Avenue", shortName: "Sunrise", price: 260, color: "#fef200" },
  { index: 27, type: "property", group: "yellow", name: "Horizon Drive", shortName: "Horizon", price: 260, color: "#fef200" },
  { index: 28, type: "utility", group: "utility", name: "City Water Works", shortName: "Water Works", price: 150, color: "#9ed1a6" },
  { index: 29, type: "property", group: "yellow", name: "Valley Road", shortName: "Valley", price: 280, color: "#fef200" },
  { index: 30, type: "corner", group: "gotojail", name: "Go to Jail", shortName: "Go to Jail", color: "#922b21" },
  { index: 31, type: "property", group: "green", name: "Crescent Park", shortName: "Crescent", price: 300, color: "#1fb25a" },
  { index: 32, type: "property", group: "green", name: "Forest Boulevard", shortName: "Forest Blvd", price: 300, color: "#1fb25a" },
  { index: 33, type: "card", group: "community", name: "City Fund", color: "#3aa6e0" },
  { index: 34, type: "property", group: "green", name: "Lakeside Drive", shortName: "Lakeside", price: 320, color: "#1fb25a" },
  { index: 35, type: "railroad", group: "railroad", name: "West Terminal", shortName: "W.Terminal", price: 200, color: "#2b2b2b" },
  { index: 36, type: "card", group: "chance", name: "Fortune", color: "#f7941d" },
  { index: 37, type: "property", group: "darkBlue", name: "Skyline Tower", shortName: "Skyline", price: 350, color: "#0072bb" },
  { index: 38, type: "tax", group: "tax", name: "Luxury Tax", shortName: "Luxury", color: "#5a5a5a" },
  { index: 39, type: "property", group: "darkBlue", name: "Diamond Court", shortName: "Diamond", price: 400, color: "#0072bb" },
];
